import { router } from 'expo-router';
import { createUserWithEmailAndPassword, updateProfile } from 'firebase/auth';
import { doc, serverTimestamp, setDoc } from 'firebase/firestore';
import React, { useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { auth, db } from '../../src/config/firebase';

export default function RegisterCompanyScreen() {
  const [companyName, setCompanyName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);

  const handleRegister = async () => {
    if (!companyName || !email || !password) {
      Alert.alert('Error', 'Please fill in all fields');
      return;
    }

    setLoading(true);
    try {
      // 1. Create Auth User
      const userCredential = await createUserWithEmailAndPassword(auth, email, password);
      const user = userCredential.user;

      // 2. Generate Company ID (auto-generated by Firestore)
      const companyRef = doc(db, 'companies', user.uid); // Using UID as Company ID for simplicity in MVP
      const companyId = user.uid;

      // 3. Create Company Document
      await setDoc(companyRef, {
        name: companyName,
        ownerId: user.uid,
        subscriptionStatus: 'trialing',
        createdAt: serverTimestamp(),
        settings: {
          nextJobNumber: 1,
          currency: 'USD'
        }
      });

      // 4. Create User Profile Document
      await setDoc(doc(db, 'users', user.uid), {
        uid: user.uid,
        email: user.email,
        displayName: `Admin (${companyName})`,
        companyId: companyId,
        role: 'admin',
        createdAt: serverTimestamp()
      });

      // 5. Update Auth Profile
      await updateProfile(user, { displayName: companyName });

      Alert.alert('Success', 'Company registered successfully!', [
        { text: 'OK', onPress: () => router.replace('/(admin)/dashboard') }
      ]);

    } catch (error: any) {
      Alert.alert('Registration Failed', error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <View style={styles.form}>
        <Text style={styles.header}>Start your 14-day trial</Text>
        
        <Text style={styles.label}>Company Name</Text>
        <TextInput
          style={styles.input}
          placeholder="Acme Plumbing Co."
          value={companyName}
          onChangeText={setCompanyName}
        />

        <Text style={styles.label}>Admin Email</Text>
        <TextInput
          style={styles.input}
          placeholder="admin@acme.com"
          autoCapitalize="none"
          keyboardType="email-address"
          value={email}
          onChangeText={setEmail}
        />

        <Text style={styles.label}>Password</Text>
        <TextInput
          style={styles.input}
          placeholder="Create a strong password"
          secureTextEntry
          value={password}
          onChangeText={setPassword}
        />

        <TouchableOpacity 
          style={styles.button} 
          onPress={handleRegister}
          disabled={loading}
        >
           {loading ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>Create Account</Text>}
        </TouchableOpacity>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flexGrow: 1, padding: 24, backgroundColor: '#fff' },
  header: { fontSize: 24, fontWeight: 'bold', marginBottom: 24, color: '#111827' },
  form: { marginTop: 10 },
  label: { fontSize: 14, fontWeight: '500', color: '#374151', marginBottom: 6 },
  input: { backgroundColor: '#f9fafb', padding: 14, borderRadius: 8, marginBottom: 16, borderWidth: 1, borderColor: '#e5e7eb', fontSize: 16 },
  button: { backgroundColor: '#10b981', padding: 16, borderRadius: 8, alignItems: 'center', marginTop: 12 },
  buttonText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
});